safe: true
lsi: false
pygments: true

exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config']

domain: accord-framework.net
title: Accord.NET Machine Learning Framework


gems:
  - jekyll-sitemap

google_analytics:
  account: UA-3114672-6

github:
  username: cesarsouza

disqus:
  id: accord-net

framework:
  version: v3.0
  download-installer: https://github.com/accord-net/framework/releases/download/v3.0.0/Accord.NET-3.0.2-installer.exe
  download-archive:   https://github.com/accord-net/framework/releases/download/v3.0.0/Accord.NET-3.0.2-archive.rar
  
